# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
  - rubocop-elegant
Layout/EndOfLine:
  EnforcedStyle: lf
Style/EvalWithLocation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Elegant/ClassInModule:
  Exclude:
    - 'lib/**/*'
    - '**/test_*.rb'
    - '**/*Test.rb'
Elegant/GoodMethodName:
  AllowedNames:
    - 'test_with_last_word_connector_but_without_oxford_comma'
    - 'test_with_max_parameter_when_array_has_more_elements'
    - 'test_with_max_parameter_when_array_has_exact_elements'
    - 'test_with_max_parameter_when_array_has_fewer_elements'
